title: Sofia Fasullo # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Sofia Fasullo. I am a first year Master in Urban Spatial Analytics and Master of City Planning student at the University of Pennsylvania. 
  <br><br>
  I am passion about affordable housing, community arts development, and storytelling through data analytics.
  <br><br>
  <a href="https://www.linkedin.com/in/sofia-fasullo-015717176/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
